using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

//this script to be added to chunk prefab/gameobject and will generate logic for the chunk

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshCollider))]
public class Chunk : MonoBehaviour
{
    //global chunk coordinate in world position
    public Vector3Int chunkCoord;

    //component references
    private MeshFilter meshFilter;
    private MeshRenderer meshRenderer;
    private MeshCollider meshCollider;

    private ChunkData chunkData;

    private _worldManager _world;

    //dynamic sized lists we will use to draw the mesh
    private List<Vector3> vertices = new List<Vector3>();
    private List<int> triangles = new List<int>();

    //UV list, UV coordinate for each vertex
    private List<Vector2> uvs = new List<Vector2>();

    //vertex count
    private int vertexIndex = 0;

    //function to be run by world manager to instantiate/configure this chunk
    public void Init(Vector3Int coord, _worldManager _world, ChunkData _data) {
        //remember chunk coordinates in world
        chunkCoord = coord;
        this._world = _world;
        this.chunkData = _data;

        meshFilter = GetComponent<MeshFilter>();
        meshRenderer = GetComponent<MeshRenderer>();
        meshCollider = GetComponent<MeshCollider>();

        //generate chunk data information (actual terrain of the chunk) , no longer generates here, generated by world
        //chunkData = new ChunkData(_world); //pass world to chunkData with dependency injection
        //chunkData.GenerateTerrain(chunkCoord);

        //no longer generate mesh when init chunk, we generate it after all chunks have been initiialized in world
        //GenerateMesh();
    }

    //generate the mesh from chunk data
    public void GenerateMesh() {
        //CLEAR OLD MESH
        vertices.Clear();
        triangles.Clear();
        uvs.Clear();
        vertexIndex = 0;

        for (int x = 0; x < VoxelData.ChunkWidth; x++) {
            for (int y = 0; y < VoxelData.ChunkHeight; y++) {
                for (int z = 0; z < VoxelData.ChunkDepth; z++) {
                    //what block it is at current coordinates
                    byte blockID = chunkData.GetVoxel(x, y, z);

                    //cycle through whole chunk, if the current block is NOT air, check if its faces need to be drawn
                    if (blockID != (byte)BlockType.Air) {
                        //send info to function to draw that block at that coordinates
                        UpdateMeshData(new Vector3Int(x, y, z), blockID);
                    }
                }
            }
        }

        RenderMesh();
    }

    //add to mesh required/to be drawn faces for this block
    private void UpdateMeshData(Vector3Int pos, byte blockID) {
        //check each direction to see if its air next to it
        for (int i = 0; i < 6; i++) {
            //add offset from voxelData to block coords to check whats next to it
            if (CheckAir(pos + VoxelData.faceChecks[i])) {

                //if check air test passes it means we need to draw this face

                //add vertices of default cube added to chunk coordonate in space
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 0]]);
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 1]]);
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 2]]);
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 3]]);

                //UV texturing ,also send face index, for expansion capabilities for different block textures based on face orientation
                AddTexture(blockID, i, pos);

                //add to list of points to draw triangles (to draw a square, we draw 2 triangles)

                //unity will take the triangle info from here and effective points from vertices
                //in triangles array from 3 in 3 will draw a triangle USING the element at triangles[value] index from vertices as a point.
                triangles.Add(vertexIndex);
                triangles.Add(vertexIndex + 1);
                triangles.Add(vertexIndex + 2);

                //secodn triangle, both combined will form the square to be drawn
                triangles.Add(vertexIndex + 0);
                triangles.Add(vertexIndex + 2);
                triangles.Add(vertexIndex + 3);

                //move index 4 pozitions forwatd cause we used 4 vertices
                vertexIndex += 4;
            }
        }
    }

    //helper function to check if block from vector3 is air , with out of bounds protection & GLOBAL CULLING - asks world to retrieve block no matter if its in this chunk or not
    private bool CheckAir(Vector3Int pos) {
        //if we are outside of chunk - GLOBAL CULLING
        if(pos.x < 0 || pos.x >= VoxelData.ChunkWidth || pos.y < 0 || pos.y >= VoxelData.ChunkHeight || pos.z < 0 || pos.z >= VoxelData.ChunkDepth) {
            Vector3Int globalPos = new Vector3Int(pos.x + (chunkCoord.x * VoxelData.ChunkWidth), pos.y, pos.z + (chunkCoord.z * VoxelData.ChunkDepth));

            //ask world manager what block is there and return true if its air, or return false if its not
            return _world.GetVoxelGlobal(globalPos) == (byte)BlockType.Air;
        }

        //if we havent exited this chunk retrieve block id locally
        byte blockID = chunkData.GetVoxel(pos.x, pos.y, pos.z);
        if (blockID == (byte)BlockType.Air) return true;

        return false;
    }

    //
    private void AddTexture(byte blockID, int faceIndex, Vector3Int pos) {
        //get texture position from texture atlas
        Vector2 texturePos = GetTexturePosition(blockID, faceIndex);

        //texture atlas coordinates simplified
        float x = texturePos.x;
        float y = texturePos.y;

        //find out the UV points coordinates, with no rotation applied

        //shrink them a little bit to prevent texture bleeding

        float shrink = 0.01f;

        Vector2[] defaultUVs = new Vector2[4];
        defaultUVs[0] = new Vector2(x + shrink, y + shrink) * VoxelData.NormalizedBlockTextureSize; //bottom left
        defaultUVs[1] = new Vector2(x + 1 - shrink, y + shrink) * VoxelData.NormalizedBlockTextureSize; //bottom right
        defaultUVs[2] = new Vector2(x + 1 - shrink, y + 1 - shrink) * VoxelData.NormalizedBlockTextureSize; //top right
        defaultUVs[3] = new Vector2(x + shrink, y + 1 - shrink) * VoxelData.NormalizedBlockTextureSize; //top left

        //logic to pseudo-randomize texture rotation based on coordinates

        int rotation = 0;

        //if it's grass side block, don't apply this logic, it will mess it up, but for every other block do it
        if (blockID == (byte)BlockType.Grass && faceIndex != 2 && faceIndex != 3) {
            //don't rotate anything
        } else if (blockID == (byte)BlockType.Planks || blockID == (byte)BlockType.Bricks || blockID == (byte)BlockType.StoneBricks ) {
            //dont rotate these blocks
        } else {
            //pseudo random number based on coordinates
            int hash = Mathf.Abs(pos.x * 123 + pos.y * 456 + pos.z * 789);
            rotation = hash % 4;
        }
        
        //add uvs to uv list
        for(int i = 0; i < 4; i++) {

            //push start index based on rotation
            int rotatedIndex = (i + rotation) % 4;
            uvs.Add(defaultUVs[rotatedIndex]);
        }
    }

    //texture retriever function moved to voxeldata
    private Vector2 GetTexturePosition(byte blockID, int faceIndex) {
        return VoxelData.GetTexturePosition(blockID, faceIndex);
    }

    //render into unity
    private void RenderMesh() {
        Mesh mesh = new Mesh();

        mesh.SetVertices(vertices);
        mesh.SetTriangles(triangles, 0); // submesh 0, aka default

        mesh.SetUVs(0, uvs);

        mesh.RecalculateNormals(); // for shadows and lights to shine correctly

        meshFilter.mesh = mesh; //send to gpu to render
        meshCollider.sharedMesh = null; //to make sure to reset collider mesh when updating mesh
        meshCollider.sharedMesh = mesh; //create collider of mesh shape
    }

    //to keep chunkData private
    public byte GetVoxelFromChunkData(int x, int y, int z) {
        return chunkData.GetVoxel(x, y, z);
    }

    public void SetVoxelToChunkData(int x, int y, int z, byte blockID) {
        chunkData.SetVoxel(x, y, z, blockID);
    }
}
