using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

//this script to be added to chunk prefab/gameobject and will generate visuals for the chunk

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshCollider))]
public class Chunk : MonoBehaviour
{
    //global chunk coordinate in world position
    public Vector3Int chunkCoord;

    //component references
    private MeshFilter meshFilter;
    private MeshRenderer meshRenderer;
    private MeshCollider meshCollider;

    private ChunkData chunkData;

    private _worldManager _world;

    //dynamic sized lists we will use to draw the mesh - USED BY ALL BLOCKS
    private List<Vector3> vertices = new List<Vector3>();
    //UV list, UV coordinate for each vertex FOR ALL BLOCKS
    private List<Vector2> uvs = new List<Vector2>();

    //triangles SEPARATED for opaque blocks (mesh level 1) and translucent blocks(mesh level 2)
    private List<int> opaqueTriangles = new List<int>();
    private List<int> transparentTriangles = new List<int>();

    private List<int> colliderTriangles = new List<int>(); // list for triangles WITH collsion

    private List<int> crossColliderTriangles = new List<int>(); // list for triangles WITH RAYCAST COLLISION BUT NO PLAYER COLLISION - for cross blocks/foliage

    //child gameobject for cross collider mesh
    private GameObject crossColliderObj;
    private MeshCollider crossMeshCollider;

    //vertex count
    private int vertexIndex = 0;

    //function to be run by world manager to instantiate/configure this chunk
    public void Init(Vector3Int coord, _worldManager _world, ChunkData _data) {
        //remember chunk coordinates in world
        chunkCoord = coord;
        this._world = _world;
        this.chunkData = _data;

        meshFilter = GetComponent<MeshFilter>();
        meshRenderer = GetComponent<MeshRenderer>();
        meshCollider = GetComponent<MeshCollider>();

        if(crossColliderObj == null) {
            //inntantiate object will hold cross collider mesh
            crossColliderObj = new GameObject("CrossCollider");
            crossColliderObj.transform.SetParent(this.transform, false);

            //set foliage layer of object
            int layerIndex = LayerMask.NameToLayer("Foliage");
            if(layerIndex != -1) {
                crossColliderObj.layer = layerIndex;
            }

            crossMeshCollider = crossColliderObj.AddComponent<MeshCollider>();
        }

        //generate chunk data information (actual terrain of the chunk) , no longer generates here, generated by world
        //chunkData = new ChunkData(_world); //pass world to chunkData with dependency injection
        //chunkData.GenerateTerrain(chunkCoord);

        //no longer generate mesh when init chunk, we generate it after all chunks have been initiialized in world
        //GenerateMesh();
    }

    //generate the mesh from chunk data
    public void BuildMeshData() {
        //CLEAR OLD MESH
        vertices.Clear();
        opaqueTriangles.Clear();
        transparentTriangles.Clear();
        colliderTriangles.Clear();
        crossColliderTriangles.Clear();
        uvs.Clear();
        vertexIndex = 0;

        for (int x = 0; x < VoxelData.ChunkWidth; x++) {
            for (int y = 0; y < VoxelData.ChunkHeight; y++) {
                for (int z = 0; z < VoxelData.ChunkDepth; z++) {
                    //what block it is at current coordinates
                    byte blockID = chunkData.GetVoxel(x, y, z);

                    //cycle through whole chunk, if the current block is NOT air, check if its faces need to be drawn
                    if (blockID != (byte)BlockType.Air) {
                        //send info to function to draw that block at that coordinates
                        UpdateMeshData(new Vector3Int(x, y, z), blockID);
                    }
                }
            }
        }

        //don't call render mesh here anymore, function only calculates mesh data
        //RenderMesh();
    }

    //add to mesh required/to be drawn faces for this block
    private void UpdateMeshData(Vector3Int pos, byte blockID) {
        //if cross model use cross logic
        if (VoxelData.IsCrossModel(blockID)) {
            DrawCrossModel(pos, blockID);
            return;
        }

        bool isTransparent = VoxelData.IsTransparent(blockID);

        //check each direction to see if its air next to it
        for (int i = 0; i < 6; i++) {
            //add offset from voxelData to block coords to check whats next to it
            if (CheckDrawFace(blockID, pos + VoxelData.faceChecks[i])) {

                //if check air test passes it means we need to draw this face

                //add vertices of default cube added to chunk coordonate in space
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 0]]);
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 1]]);
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 2]]);
                vertices.Add(pos + VoxelData.voxelVerts[VoxelData.voxelTris[i, 3]]);

                //UV texturing ,also send face index, for expansion capabilities for different block textures based on face orientation
                AddTexture(blockID, i, pos);

                //add to list of points to draw triangles (to draw a square, we draw 2 triangles)

                //unity will take the triangle info from here and effective points from vertices
                //in triangles array from 3 in 3 will draw a triangle USING the element at triangles[value] index from vertices as a point.
                //first 3 - first tirangle, next 3 - secodn triangle, both combined will form the square to be drawn

                //ADD in corresponding list based on block transparency
                if (isTransparent) {
                    transparentTriangles.Add(vertexIndex);
                    transparentTriangles.Add(vertexIndex + 1);
                    transparentTriangles.Add(vertexIndex + 2);

                    transparentTriangles.Add(vertexIndex + 0);
                    transparentTriangles.Add(vertexIndex + 2);
                    transparentTriangles.Add(vertexIndex + 3);
                } else {
                    opaqueTriangles.Add(vertexIndex);
                    opaqueTriangles.Add(vertexIndex + 1);
                    opaqueTriangles.Add(vertexIndex + 2);

                    opaqueTriangles.Add(vertexIndex + 0);
                    opaqueTriangles.Add(vertexIndex + 2);
                    opaqueTriangles.Add(vertexIndex + 3);
                }

                //if it has collision add to vertices colliders list
                if (VoxelData.HasCollision(blockID)) {
                    colliderTriangles.Add(vertexIndex);
                    colliderTriangles.Add(vertexIndex + 1);
                    colliderTriangles.Add(vertexIndex + 2);

                    colliderTriangles.Add(vertexIndex + 0);
                    colliderTriangles.Add(vertexIndex + 2);
                    colliderTriangles.Add(vertexIndex + 3);
                }

                //move index 4 pozitions forwatd cause we used 4 vertices
                vertexIndex += 4;
            }
        }
    }

    //add cross vertices for foilage
    private void DrawCrossModel(Vector3Int pos, byte blockID) {
        //we need to draw 4 faces to see it from every angle

        //draw the 2 diagonals in both forward and backward order
        AddCrossFace(pos, blockID, new Vector3(0, 0, 0), new Vector3(1, 0, 1), new Vector3(1, 1, 1), new Vector3(0, 1, 0)); //diag 1 front
        //diag 1 backward
        AddCrossFace(pos, blockID, new Vector3(1, 0, 1), new Vector3(0, 0, 0), new Vector3(0, 1, 0), new Vector3(1, 1, 1));

        //diag 2
        AddCrossFace(pos, blockID, new Vector3(0, 0, 1), new Vector3(1, 0, 0), new Vector3(1, 1, 0), new Vector3(0, 1, 1)); //forward
        AddCrossFace(pos, blockID, new Vector3(1, 0, 0), new Vector3(0, 0, 1), new Vector3(0, 1, 1), new Vector3(1, 1, 0)); //backward

    }

    //helper function for above
    private void AddCrossFace(Vector3Int pos, byte blockID, Vector3 v1, Vector3 v2, Vector3 v3, Vector3 v4) {
        vertices.Add(pos + v1);
        vertices.Add(pos + v2);
        vertices.Add(pos + v3);
        vertices.Add(pos + v4);

        AddTexture(blockID, 0, pos);

        //go to trnasparent submesh
        transparentTriangles.Add(vertexIndex);
        transparentTriangles.Add(vertexIndex + 1);
        transparentTriangles.Add(vertexIndex + 2);

        transparentTriangles.Add(vertexIndex + 0);
        transparentTriangles.Add(vertexIndex + 2);
        transparentTriangles.Add(vertexIndex + 3);

        //also add to cross collider triangles
        crossColliderTriangles.Add(vertexIndex);
        crossColliderTriangles.Add(vertexIndex + 1);
        crossColliderTriangles.Add(vertexIndex + 2);

        crossColliderTriangles.Add(vertexIndex + 0);
        crossColliderTriangles.Add(vertexIndex + 2);
        crossColliderTriangles.Add(vertexIndex + 3);

        vertexIndex += 4;
    }

    //new check block function for culling
    //logic is as following:
        //if we are opaque and neighbour is transparent, draw ourselves
        //if we are transparent and neighbour is transparent, don't draw ourselves
        //if we are transparent and neighbour is opaque, don't draw ourselves
        //basically always yield priority to the opaque block, and when draw don't draw ourselves for continuity
    private bool CheckDrawFace(byte blockID, Vector3Int neighbourPos) {

        byte neighbourID = GetBlockAt(neighbourPos);

        //if neighbour is air, draw this block's face
        if (neighbourID == (byte)BlockType.Air || VoxelData.IsCrossModel(neighbourID)) return true;

        bool currentIsTransparent = VoxelData.IsTransparent(blockID);
        bool neighbourIsTransparent = VoxelData.IsTransparent(neighbourID);

        //if neighbour is transparent and we are not, always draw ourselves
        if (!currentIsTransparent && neighbourIsTransparent) return true;

        //if we are transparent and neighbour is the same, don't draw ourselves, for glass/water continuity
        if (currentIsTransparent && neighbourID == blockID) {
            //otherwise dont draw
            return false;
        }
        

        //rest of cases, opaque-opaque or glass with opaque neighbour, don't draw ourselves
        return false;
    }

    //helper function for grabbing neighbours blockID, if block requested is in chunk or if its in next chunk
    private byte GetBlockAt(Vector3Int pos) {
        //if we are outside of chunk grab him globally
        if (pos.x < 0 || pos.x >= VoxelData.ChunkWidth || pos.y < 0 || pos.y >= VoxelData.ChunkHeight || pos.z < 0 || pos.z >= VoxelData.ChunkDepth) {
            //convert to global coordinates
            Vector3Int globalPos = new Vector3Int(pos.x + (chunkCoord.x * VoxelData.ChunkWidth), pos.y, pos.z + (chunkCoord.z * VoxelData.ChunkDepth));

            //ask world manager what block is there and return it
            return _world.GetVoxelGlobal(globalPos);
        }
        //else just return locally
        return chunkData.GetVoxel(pos.x, pos.y, pos.z);
    }

    //no longer used - we use CheckDrawFace to support transparent blocks culling aswell
    //helper function to check if block from vector3 is air , with out of bounds protection & GLOBAL CULLING - asks world to retrieve block no matter if its in this chunk or not
    private bool CheckAir(Vector3Int pos) {
        //if we are outside of chunk - GLOBAL CULLING
        if(pos.x < 0 || pos.x >= VoxelData.ChunkWidth || pos.y < 0 || pos.y >= VoxelData.ChunkHeight || pos.z < 0 || pos.z >= VoxelData.ChunkDepth) {
            Vector3Int globalPos = new Vector3Int(pos.x + (chunkCoord.x * VoxelData.ChunkWidth), pos.y, pos.z + (chunkCoord.z * VoxelData.ChunkDepth));

            //ask world manager what block is there and return true if its air, or return false if its not
            return _world.GetVoxelGlobal(globalPos) == (byte)BlockType.Air;
        }

        //if we havent exited this chunk retrieve block id locally
        byte blockID = chunkData.GetVoxel(pos.x, pos.y, pos.z);
        if (blockID == (byte)BlockType.Air) return true;

        return false;
    }

    //
    private void AddTexture(byte blockID, int faceIndex, Vector3Int pos) {
        //get texture position from texture atlas
        Vector2 texturePos = GetTexturePosition(blockID, faceIndex);

        //texture atlas coordinates simplified
        float x = texturePos.x;
        float y = texturePos.y;

        //find out the UV points coordinates, with no rotation applied

        //shrink them a little bit to prevent texture bleeding

        float shrink = 0.01f;

        Vector2[] defaultUVs = new Vector2[4];
        defaultUVs[0] = new Vector2(x + shrink, y + shrink) * VoxelData.NormalizedBlockTextureSize; //bottom left
        defaultUVs[1] = new Vector2(x + 1 - shrink, y + shrink) * VoxelData.NormalizedBlockTextureSize; //bottom right
        defaultUVs[2] = new Vector2(x + 1 - shrink, y + 1 - shrink) * VoxelData.NormalizedBlockTextureSize; //top right
        defaultUVs[3] = new Vector2(x + shrink, y + 1 - shrink) * VoxelData.NormalizedBlockTextureSize; //top left

        //logic to pseudo-randomize texture rotation based on coordinates

        int rotation = 0;

        //if it's grass side block, don't apply this logic, it will mess it up, but for every other block do it
        if (blockID == (byte)BlockType.Grass && faceIndex != 2 && faceIndex != 3) {
            //don't rotate anything
        } else if (blockID == (byte)BlockType.Planks || blockID == (byte)BlockType.Bricks || blockID == (byte)BlockType.StoneBricks || blockID == (byte)BlockType.Wood || VoxelData.IsTransparent(blockID)) {
            //dont rotate these blocks
        } else {
            //pseudo random number based on coordinates
            int hash = Mathf.Abs(pos.x * 123 + pos.y * 456 + pos.z * 789);
            rotation = hash % 4;
        }
        
        //add uvs to uv list
        for(int i = 0; i < 4; i++) {

            //push start index based on rotation
            int rotatedIndex = (i + rotation) % 4;
            uvs.Add(defaultUVs[rotatedIndex]);
        }
    }

    //texture retriever function moved to voxeldata
    private Vector2 GetTexturePosition(byte blockID, int faceIndex) {
        return VoxelData.GetTexturePosition(blockID, faceIndex);
    }

    //render async into unity
    public void ApplyMesh() {
        Mesh mesh = new Mesh();

        mesh.SetVertices(vertices);
        mesh.SetUVs(0, uvs);

        //split mesh into 2 submeshes, one with opaque material, one with translucent material
        mesh.subMeshCount = 2;
        mesh.SetTriangles(opaqueTriangles, 0); // mat 0
        mesh.SetTriangles(transparentTriangles, 1); // mat 1

        if(vertices.Count> 0) {
            mesh.RecalculateNormals(); // for shadows and lights to shine correctly
        }

        meshFilter.mesh = mesh; //send to gpu to render

        //separate collisi0on mesh from our collision triangles
        if(colliderTriangles.Count > 0) {
            Mesh collisionMesh = new Mesh();
            collisionMesh.SetVertices(vertices);
            collisionMesh.SetTriangles(colliderTriangles, 0);

            meshCollider.sharedMesh = null; //to make sure to reset collider mesh when updating mesh
            meshCollider.sharedMesh = collisionMesh; //set collision mesh
        } else {
            meshCollider.sharedMesh = null;
        }


        if (crossColliderTriangles.Count > 0) {
            //collision mesh for cross models/foliage blocks you can pass throguh
            Mesh crossMesh = new Mesh();
            crossMesh.SetVertices(vertices);
            crossMesh.SetTriangles(crossColliderTriangles, 0);
            crossMeshCollider.sharedMesh = null;
            crossMeshCollider.sharedMesh = crossMesh;
        } else {
            crossMeshCollider.sharedMesh = null;
        }
        
    }

    //to keep chunkData private
    public byte GetVoxelFromChunkData(int x, int y, int z) {
        return chunkData.GetVoxel(x, y, z);
    }

    public void SetVoxelToChunkData(int x, int y, int z, byte blockID) {
        chunkData.SetVoxel(x, y, z, blockID);
    }
}
